export const SHOW_ERROR = 'SHOW_ERROR';
export const GET_REPOSITORIES = 'GET_REPOSITORIES';
export const GET_CONTRIBUTORS = 'GET_CONTRIBUTORS';
export const SHOW_LOADING = 'SHOW_LOADING';
export const HIDE_LOADING = 'HIDE_LOADING';
export const SET_ACTIVE_REPOSITORY = 'SET_ACTIVE_REPOSITORY';
